// This file is in public domain.

#pragma once
#include <winioctl.h>

#define _RKH_ACCESS_CTL_CODE(_Function) \
CTL_CODE(FILE_DEVICE_UNKNOWN, _Function, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RKH_GET_DEVICE_GENERATION _RKH_ACCESS_CTL_CODE(0x801)

#define IOCTL_RKH_CAN_SOFT_RESET _RKH_ACCESS_CTL_CODE(0x802)

#define IOCTL_RKH_CAN_HARD_RESET _RKH_ACCESS_CTL_CODE(0x803)

#define IOCTL_RKH_DO_SOFT_RESET _RKH_ACCESS_CTL_CODE(0x804)

#define IOCTL_RKH_DO_HARD_RESET _RKH_ACCESS_CTL_CODE(0x805)

#define IOCTL_RKH_INSTALL_DICPROTECT _RKH_ACCESS_CTL_CODE(0x806)

#define ERROR_GENERATION_NOT_SUPPORTED          0x1200
#define ERROR_NKFORCECLEANBOOT_NOT_FOUND        0x1201
